version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - pinkahd
  ignore:
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.8
  - dependency-name: jsdoc-to-markdown
    versions:
    - 7.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
